name: unit-testing

on: push

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v2
      - name: test application
        run: make test